name: Support
description: You have a question about achieving a particular effect or need help with using the project.
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using `aanas0sayed/docker-ltspice` Docker image!

        If you are looking for support, please check out our documentation.
        <!-- TODO: Add documentation link -->
        <!-- * [Documentation](https://example.com/docs) -->
  - type: textarea
    id: question
    attributes:
      label: What is your question?
      description: Provide a detailed description of your question or the help you need with the Docker image.
    validations:
      required: true
  - type: checkboxes
    id: self-checks
    attributes:
      label: Checklist before submitting a question
      description: Please verify all the following items before submitting a question. All options must be selected.
      options:
        - label: I searched issues in this repository and couldn't find such question/problem
          required: true
        - label: I searched for a solution online and couldn't find it
          required: true
        - label: I searched on Stack Overflow for a solution and couldn't find it
          required: true
        - label: I read the project's README.md file
          required: true
        - label: I am using the latest version of the Docker image
          required: true
        - label: All dependencies are up to date
          required: true
